import type { NextPage } from 'next'
import Head from 'next/head'
import { Footer } from '../components/footer'
import { Header } from '../components/header'
import * as globalStyles from '../styles/global.css'

const Home: NextPage = () => {
  return (
    <div className={globalStyles.container}>
      <Head>
        <title>RB.ME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <p>Hello, I&apos;m Rick Booth</p>
      </main>

      <Footer />
    </div>
  )
}

export default Home
